### ISSUE TITLE
Thanks for the code..

### ISSUE THREAD

**Issue by creatorscan** [wnhsu/SpeechVAE#1]
Great thanks for sharing the code. I have a question about the range of log-likelihood to expect with respect to TIMIT data. I am getting inbetween range(-200,-400) for Filter bank features. Thank you for your help.

**Comment by wnhsu** [comment]
hi creatorscan, I'm wondering if you are talking about logp(x|z) or the lower bound of the marginal log likelihood. If I remember correctly, the logp(x|z) is supposed to be around zero. Make sure you normalize the input before feeding to the network.

Either way, I would recommend using visual inspection on the reconstructed Mel spectrogram to determine the quality. The repo has provided a few sample reconstruction, which you might like to use as a reference.
