### ISSUE TITLE
Failing at step 4

### ISSUE THREAD

**Issue by vivek-sethia** [wnhsu/SpeechVAE#3]
./local/spec_data_prep.sh: stage 4, generate dataset.cfg
steps/make_dataset_conf.sh /home/ideabay/Documents/vivek/Thesis/SpeechVAE/egs/timit/data/spec_scp/train /home/ideabay/Documents/vivek/Thesis/SpeechVAE/egs/timit/data/spec_scp/dev /home/ideabay/Documents/vivek/Thesis/SpeechVAE/egs/timit/data/spec_scp/test /home/ideabay/Documents/vivek/Thesis/SpeechVAE/egs/timit/data/spec_scp/train/dataset.cfg
steps/make_dataset_conf.sh: **/../../../../../SpeechVAE/egs/timit/data/spec_scp/train/feats.scp not found**

**Comment by wnhsu** [comment]
You might have ran the scripted a few times and previous run wasn't successful.
Remove the ./egs/timit/data and all the data folder in $KALDI_ROOT/egs/timit/s5/data, re-run the script again and make sure every step was successful.

**Comment by vivek-sethia** [comment]
During make all , the following link is not reached

**http://openfst.cs.nyu.edu/twiki/pub/FST/FstDownload/openfst-1.3.4.tar.gz** 

and also gets an error at the end like this

```
/usr/bin/ld: cannot find -lboost_python3
collect2: error: ld returned 1 exit status
Makefile:29: recipe for target 'kaldi_io_internal.so' failed
make[2]: *** [kaldi_io_internal.so] Error 1
make[2]: Leaving directory '/home/ideabay/Documents/vivek/SpeechVAE/kaldi_python/kaldi-python'
Makefile:10: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ideabay/Documents/vivek/SpeechVAE/kaldi_python'
Makefile:19: recipe for target 'kaldi_python' failed
make: *** [kaldi_python] Error 2
```


Do you know what should be done for this?

**Comment by wnhsu** [comment]
seems like you are missing libboost_python3 library. you can refer to here for some instructions.
[https://github.com/openai/roboschool/issues/133](url)
i'm closing this as this issue is not directly related to this project.
