### ISSUE TITLE
about split speech spectrogram into "images"

### ISSUE THREAD

**Issue by tuanad121** [wnhsu/SpeechVAE#4]
Hi, I read your paper and it said the sequence of features of each sentence is splitted into 80 (or 200) frame chunks. Each chunk is an input "image" for the Convolution VAE. I guess for each sentence, the number of chunks is equal to the number of frames. I'm looking for the script where you split each sentence into "images" but I couldn't find it in the repo. I know it can be a simple function but it will be very helpful for me. Where can I find the part in your repo? 
Thanks

**Comment by wnhsu** [comment]
Hi,
Please see src/datasets/kaldi_ra_dataset.py
The variable seg_len determines the width (in frames).

**Comment by tuanad121** [comment]
Alright, I found the part. Thanks for your help ^^
