### ISSUE TITLE
fail to run run_spec.h

### ISSUE THREAD

**Issue by prashantmaheshwari94** [wnhsu/SpeechVAE#5]
No file name parse_options.sh. 
What is the purpose of this file? It is used at six places but not committed.
Please help.
Thanks

**Comment by wnhsu** [comment]
Hi, have you installed Kaldi and set the `KALDI_ROOT` correspondingly in `path.sh`?
You should be able to find `parse_options.sh` under `$KALDI_ROOT/egs/wsj/s5/utils`

The script is used to parse arguments passed to `*.sh` scripts.
